name: CI Pipeline for AutomationPythonProjectBriefCam

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull request targeting 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # The job will run on an Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Set up Docker Buildx for multi-platform builds

      - name: Build Docker image
        run: |
          docker build -t automation-python-app .  # Build the Docker image using your Dockerfile

      - name: Run tests inside Docker container
        run: |
          docker run --rm automation-python-app pytest  # Run pytest inside the Docker container

      - name: Clean up Docker image
        run: |
          docker rmi automation-python-app  # Optionally clean up the Docker image after testing
