name: Build and Test Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # The job will run on an Ubuntu runner

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t my-python-app .

      # Step 4: Run tests using Docker
      - name: Run tests inside Docker container
        run: |
          docker run --rm my-python-app pytest  # Run pytest inside the container

      # Step 5: Optionally, run the application (uncomment if needed)
      # - name: Run application in Docker container
      #   run: |
      #     docker run -d -p 80:80 my-python-app  # Start the app
